### ISSUE TITLE
New Auto1111 versions are using 256SHA Hash, which breaks merge board and causes other issues

### ISSUE THREAD

**Issue by RandomInternetPreson** [bbc-mc/sdweb-merge-board#13]
Hello, I really like merge-board., and I appreciate that you invested your time to create something so useful!  I use it as part of my work flow and rely on it a lot.  A couple of days ago Auto1111 was updated to use SHA256 hash values.

This breaks merge-board and also means there is a disconnect (or will be for many) between the old traditional hash values people share, use online, and store in their .png metadata.  The SHA256 hash value is not similar to the old hash values.

I wanted to bring this to you attention, maybe you can update merge board and improve upon it to be a link between the old and new S256SHA hash values?

There is code here that derives the old hash values: https://github.com/etherealxx/oneclick-showmodelhash

Here is the original thread on Auto1111, people were originally reporting it as a bug (myself included): https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/6761

Here is my [Feature Request] for Auto1111: https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/6818
I don't know if they will implement anything to bridge the old and new hash values.

Additionally, maybe this will save you some time, but the new hashes are stored in a file called "cache.json" in the root install of Auto1111.  The hashes only populate when their representative model is loaded.  This means Auto1111 doesn't compute all hash values in the model directory upon startup.

In my opinion, it did all the hash values very quickly, I have a few symbolic links on various drives and a lot of models and it maybe adds only a few seconds to the Auto1111 boot time.

Anyway, I hope you find this useful, and thanks again for making merge-board 🥇

**Comment by ZeroCool22** [comment]
Merge models functionality is really important for creating more interesting models and inpainting models too!
I guess i will keep working with the old commit without this hashes change.

**Comment by RandomInternetPreson** [comment]
That's what I'm doing, This guy https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/6761#issue-1533606537 estimates the date it happened and provides a repo link.  I am using one slightly older than that one, and all my plugins work.

**Comment by bbc-mc** [comment]
Hi, I'm happy to hear my tool help you enjoy !

I want to understand details what are you concerning about.

**hash value on log**
If you are talking about hash value which saved on log file, I have plan to change log system to save sha256 also.
I'm watching changes around sha256 things, and already add sha256 support on other my Extension [Merge Block Weighted on this commit](https://github.com/bbc-mc/sdweb-merge-block-weighted-gui/commit/7988953b2c3f384890d5fd08e2ca2d66f4002e54) to save old-hash and new sha256 both.
Auto1111 still have old hash generation code and param, we can use it.

**Model Selection**
If you are talking about "Wrong model selection by same hash" problem, (In my understanding, this happens when uses t2i or i2i from genration info on png), Merge-Board is not affected because it uses model selection dropdown list by model name.

**hash value saved on GenerationInfo on png**
If about Generation info hash value on png, merge-board is out of scope.

Let me know which one (or other?) issue/subject are you concern about?

**Comment by ZeroCool22** [comment]
> Hi, I'm happy to hear my tool help you enjoy !
> 
> I want to understand details what are you concerning about.
> 
> **hash value on log** If you are talking about hash value which saved on log file, I have plan to change log system to save sha256 also. I'm watching changes around sha256 things, and already add sha256 support on other my Extension [Merge Block Weighted on this commit](https://github.com/bbc-mc/sdweb-merge-block-weighted-gui/commit/7988953b2c3f384890d5fd08e2ca2d66f4002e54) to save old-hash and new sha256 both. Auto1111 still have old hash generation code and param, we can use it.
> 
> **Model Selection** If you are talking about "Wrong model selection by same hash" problem, (In my understanding, this happens when uses t2i or i2i from genration info on png), Merge-Board is not affected because it uses model selection dropdown list by model name.
> 
> **hash value saved on GenerationInfo on png** If about Generation info hash value on png, merge-board is out of scope.
> 
> Let me know which one (or other?) issue/subject are you concern about?

![Screenshot_16](https://user-images.githubusercontent.com/13344308/213191355-71e613f3-0c91-4930-80ec-38301bb13efb.jpg)

I'm talking about the Hashes on the **Drop Down list**.

You can say, ok, but you can still be seeing it in the txt file, but the hashes are not the same as the old ones.

And i hear the change broke the ability to **Merge models**?

**Comment by RandomInternetPreson** [comment]
WOW thank you for the reply, I am so glad you are already aware of the hash changes <3.  I love merge board so much, thank you, thank you, thank you!!!  Saving both hashes like your comment indicates, is a great solution :)

Specifically what breaks in merge board right now is this option (list-Up checkpoints), I think it's because the old hashes are not automatically generated upon startup like the previous versions of Auto1111:

![Untitled](https://user-images.githubusercontent.com/6488699/213207264-c449dc56-10b9-4d55-94f3-ca7abdd2a1c6.png)
![1Untitled](https://user-images.githubusercontent.com/6488699/213207302-60e97e47-8daf-4b68-be82-e44bc8afbbd9.png)

I used this option a lot, I can do a ctrl+f and search for specific old hashes, maybe you can include the old and new hashes in this option too?

Really appreciate the plugin, seriously my most used feature!

**Comment by RandomInternetPreson** [comment]
@ZeroCool22, I don't think we are ever going to get the hashes back in the drop down menu, but hopefully the List-Up checkpoints option will be updated and can be used as a replacement.

**Comment by RandomInternetPreson** [comment]
@bbc-mc Thanks again for the response, one feature that I think would  add a lot of utility to merge-board is being able to click on a model in the "List-up Checkpoints" database and have it load into Auto1111.  

The list "List-Up Checkpoints" generates is fantastic! but I need to go back to the drop down UI to select my model, it would be so awesome if I could just click the model tin the generated List-Up list and load the model that way.

**Comment by bbc-mc** [comment]
> WOW thank you for the reply, I am so glad you are already aware of the hash changes <3. I love merge board so much, thank you, thank you, thank you!!! Saving both hashes like your comment indicates, is a great solution :)
> Specifically what breaks in merge board right now is this option (list-Up checkpoints), I think it's because the old hashes are not automatically generated upon startup like the previous versions of Auto1111:

@RandomInternetPreson
Thanks for detail, I understand what you meant "broken".

Yes, "Model list" is now not working because data structure on AUTO1111 is changed at SHA256 kind commit.
And, as I said above, now preparing update to show "old hash" and "sha256" both, this can be help.

Just two point I want to make clear.
- Old hash value is still calcurated at start time and NOT CHANGED.
So, that is up to decision of AUTOMATIC1111 whether show old hash on Dropdown or not. Not mine. Talk to AUTOMATIC1111 on his repo.
- "merge board" is not using hash for Merging, just showing list. So there is nothing broken about "Merge" Model.

btw,
Your idea is interesting to select model from this list.
I also have looong list on dropdown.
I'll think about that.

**Comment by RandomInternetPreson** [comment]
Totally understand, yeah merge board is still merging models well. I should have been more clear in my original post, sorry about that. 

Interesting, I didn't know the old hashes were still computed at launch, that's good to know.  I was worried Auto1111 nuked the old computation methodology.

Merge-Board rocks!!

**Comment by RandomInternetPreson** [comment]
Also, I love that the recipes are saved automatically...god that is so useful!

**Comment by RandomInternetPreson** [comment]
@bbc-mc OMFG Thank you kind internet stranger, I just tried your updated code with the new Auto1111 and the merge list is back and working.... Thank you so much :) 🥇

**Comment by bbc-mc** [comment]
@RandomInternetPreson
Just good timing of complete code, and need other update.
Anyway, enjoy !
