### ISSUE TITLE
[Feature Request] Allow negative M values/ Add Subtract Difference 

### ISSUE THREAD

**Issue by jangofett890** [bbc-mc/sdweb-merge-board#2]
This can be used to remove content, or style overtraining from a model.
For example, NAI is anime styled but has much greater ability at doing NSFW content, meanwhile WD is SFW mostly and only adds anime/beautification.
If we remove WD from NAI we get a NAI-Tagset model, anything NAI was trained to make besides the anime style can now be injected into other models
For example, here's a recipe for injecting it into the Cafe model:
```
# Recipe 
NAI_AnimeStyleSurpressed = model + wd-v1-3-float16 + SD-v1.4, -0.35, ckpt
Cafe+NAITagging = cafe-instagram-unofficial-test-epoch-9-140k-images-fp32 + __O1__ + SD-v1.4, 0.5, ckpt

# Variables(System) 
__O1__

# Variables(User defined)
```

**Comment by bbc-mc** [comment]
Thank you for request.

Actually I know your request has already met.


I know I'm not validating `M` value when "Send to Recipe", so if you set minus value in Recipe, `M` value on Multi-Merge UI become minus value.

Note: if you change `M` value on "Multi-Merge" UI, UI validation will work to keep value between `0` to `1`. So if you dont touch `M` value in UI, `M` value stays minus, and you can process merge with minus value!


So, please try your recipe. "Parse" and "Send" and you found `M1` value is set to `- 0.35`.
```
NAI_AnimeStyleSurpressed = __NAI__ + __WD__ + __SD__, -0.35, ckpt
Cafe+NAITagging = __CAFE__ + __O1__ + __SD__, 0.5, ckpt
```

Note: idk what happen when merging with minus value. This extension is only UI, and merging method is AUTOMATIC1111's function. Im intended to keep freeness of functions params (like this minus values) because I know try and error makes a lot of fun! 
![#2_request_m_minus_value_can_set](https://user-images.githubusercontent.com/2047286/204860712-3aae4724-7dc8-4e54-963b-fa41834ac60f.png)
